name: SonarCloud Analysis
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
 
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
 
    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x # Change this to match your .NET version
 
    # Step 3: Install dependencies
    - name: Restore dependencies
      run: dotnet restore
 
    # Step 4: Build the solution
    - name: Build the solution
      run: dotnet build --no-restore --configuration Release
 
    # Step 5: Run tests
    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger:trx
 
    # Step 6: SonarCloud Analysis
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: 379d21056c9410f380f6d8e392bf6e8f01cdd1f3
        SONAR_ORG: saranyaramasamy96
      run: |
        dotnet tool install --global dotnet-sonarscanner
        export PATH="$PATH:/home/runner/.dotnet/tools"
        dotnet sonarscanner begin \
          /k:"SaranyaRamasamy96/SonarCloudPOC" \
          /o:"saranyaramasamy96" \
          /d:sonar.login="379d21056c9410f380f6d8e392bf6e8f01cdd1f3" \
          /d:sonar.host.url="https://sonarcloud.io"
        dotnet build --no-restore
        dotnet sonarscanner end /d:sonar.login="379d21056c9410f380f6d8e392bf6e8f01cdd1f3"
